name: GitHub Pipeline Demo
on: [push]
jobs:
  Buildar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout para branch main
        uses: actions/checkout@v2
      - name: configura NodeJs
        uses: actions/setup-node@v2
        with:
            node-version: "16.x"
      - name: Instala Yarn
        run: npm install -g yarn
      - name: Iniciar Yarn
        run: yarn install
      - name: Buildar projeto
        run: yarn build
